"""test

Revision ID: 262ba8a09555
Revises: d710d7cbba58
Create Date: 2021-05-13 15:31:52.861842

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
from sqlalchemy.dialects.postgresql import UUID

revision = '262ba8a09555'
down_revision = 'd710d7cbba58'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('education',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('user_id', UUID(), nullable=True),
        sa.Column('edu_type', sa.Enum('MIDDLE_SCHOOL', 'HIGH_SCHOOL', 'UNIVERSITY', 'MASTER', 'PHD', name='edutype'),
            nullable=False),
        sa.Column('name', sa.String(length=100), nullable=False),
        sa.Column('city', sa.String(length=100), nullable=False),
        sa.Column('start_date', sa.Date(), nullable=False),
        sa.Column('end_date', sa.Date(), nullable=False),
        sa.ForeignKeyConstraint(['user_id'], ['usertable.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_table('experience',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('user_id', UUID(), nullable=True),
        sa.Column('position', sa.String(length=100), nullable=False),
        sa.Column('employer', sa.String(length=100), nullable=False),
        sa.Column('city', sa.String(length=100), nullable=False),
        sa.Column('start_date', sa.Date(), nullable=False),
        sa.Column('end_date', sa.Date(), nullable=False),
        sa.Column('description', sa.String(length=1000), nullable=True),
        sa.ForeignKeyConstraint(['user_id'], ['usertable.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.add_column('usertable', sa.Column('phone_number', sa.String(length=50), nullable=True))
    op.add_column('usertable', sa.Column('location', sa.String(length=50), nullable=True))
    op.add_column('usertable', sa.Column('birthdate', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('usertable', 'birthdate')
    op.drop_column('usertable', 'location')
    op.drop_column('usertable', 'phone_number')
    op.drop_table('experience')
    op.drop_table('education')
    # ### end Alembic commands ###
