"""disabilities

Revision ID: 2cfa00d60652
Revises: b76743282378
Create Date: 2021-05-13 23:28:42.920811

"""
import sqlalchemy as sa
# revision identifiers, used by Alembic.
from sqlalchemy.dialects.postgresql import UUID

from alembic import op

revision = "2cfa00d60652"
down_revision = "b76743282378"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "disability",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", UUID(), nullable=True),
        sa.Column(
            "type", sa.Enum("VISUAL", "HEARING", "SPEECH", "LOCOMOTOR", "NEURAL", name="disabilitytype"), nullable=False
        ),
        sa.Column("level", sa.Enum("LOW", "MEDIUM", "ADVANCED", "HIGH", name="disabilitylevel"), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["usertable.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.drop_column("usertable", "hearing")
    op.drop_column("usertable", "visual")
    op.drop_column("usertable", "locomotor")
    op.drop_column("usertable", "neural")
    op.drop_column("usertable", "speech_impediment")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("usertable", sa.Column("speech_impediment", sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column("usertable", sa.Column("neural", sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column("usertable", sa.Column("locomotor", sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column("usertable", sa.Column("visual", sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column("usertable", sa.Column("hearing", sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_table("disability")
    # ### end Alembic commands ###
