"""languages

Revision ID: 3d45e98b9c12
Revises: 4e3dd7095cf5
Create Date: 2021-05-13 21:15:14.269126

"""
import sqlalchemy as sa
# revision identifiers, used by Alembic.
from sqlalchemy.dialects.postgresql import UUID

from alembic import op

revision = "3d45e98b9c12"
down_revision = "4e3dd7095cf5"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "language",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", UUID(), nullable=True),
        sa.Column("language", sa.String(length=40), nullable=False),
        sa.Column("level", sa.Enum("BEGINNER", "MEDIUM", "ADVANCED", "NATIVE", name="languagelevel"), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["usertable.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("language")
    # ### end Alembic commands ###
