"""optionalname

Revision ID: 4e3dd7095cf5
Revises: 262ba8a09555
Create Date: 2021-05-13 19:20:16.332572

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "4e3dd7095cf5"
down_revision = "262ba8a09555"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("usertable", "first_name", existing_type=sa.VARCHAR(length=40), nullable=True)
    op.alter_column("usertable", "last_name", existing_type=sa.VARCHAR(length=40), nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("usertable", "last_name", existing_type=sa.VARCHAR(length=40), nullable=False)
    op.alter_column("usertable", "first_name", existing_type=sa.VARCHAR(length=40), nullable=False)
    # ### end Alembic commands ###
