"""checkboxes

Revision ID: b76743282378
Revises: da9c455522a7
Create Date: 2021-05-13 22:46:29.278471

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "b76743282378"
down_revision = "da9c455522a7"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("usertable", sa.Column("creativity", sa.Boolean(), nullable=True))
    op.add_column("usertable", sa.Column("analytic_thinking", sa.Boolean(), nullable=True))
    op.add_column("usertable", sa.Column("communication", sa.Boolean(), nullable=True))
    op.add_column("usertable", sa.Column("teamwork", sa.Boolean(), nullable=True))
    op.add_column("usertable", sa.Column("adaptive", sa.Boolean(), nullable=True))
    op.add_column("usertable", sa.Column("walking", sa.Boolean(), nullable=True))
    op.add_column("usertable", sa.Column("painting", sa.Boolean(), nullable=True))
    op.add_column("usertable", sa.Column("video_games", sa.Boolean(), nullable=True))
    op.add_column("usertable", sa.Column("reading", sa.Boolean(), nullable=True))
    op.add_column("usertable", sa.Column("movies", sa.Boolean(), nullable=True))
    op.add_column("usertable", sa.Column("writing", sa.Boolean(), nullable=True))
    op.add_column("usertable", sa.Column("singing", sa.Boolean(), nullable=True))
    op.add_column("usertable", sa.Column("music", sa.Boolean(), nullable=True))
    op.add_column("usertable", sa.Column("audio_books", sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("usertable", "audio_books")
    op.drop_column("usertable", "music")
    op.drop_column("usertable", "singing")
    op.drop_column("usertable", "writing")
    op.drop_column("usertable", "movies")
    op.drop_column("usertable", "reading")
    op.drop_column("usertable", "video_games")
    op.drop_column("usertable", "painting")
    op.drop_column("usertable", "walking")
    op.drop_column("usertable", "adaptive")
    op.drop_column("usertable", "teamwork")
    op.drop_column("usertable", "communication")
    op.drop_column("usertable", "analytic_thinking")
    op.drop_column("usertable", "creativity")
    # ### end Alembic commands ###
